// Sample catalogue used by the "Seed sample products" button in the admin
// panel, so the store isn't empty on first run. Placeholder images come from
// picsum.photos — replace with real product photos via the admin panel.

function img(seed, w = 800, h = 1000) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const SEED_PRODUCTS = [
  {
    name: "Oversized Boxy Tee",
    category: "men",
    price: 650,
    compareAtPrice: null,
    isNew: true,
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Espresso", "Sand"],
    images: [img("night-tee-1"), img("night-tee-2")],
    description: "Heavyweight cotton boxy tee with a dropped shoulder. Garment-dyed for a soft, worn-in feel.",
  },
  {
    name: "Relaxed Cargo Pants",
    category: "men",
    price: 1150,
    compareAtPrice: 1450,
    isNew: false,
    inStock: true,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Espresso", "Black"],
    images: [img("night-cargo-1"), img("night-cargo-2")],
    description: "Relaxed-fit cargo pants with utility pockets and an adjustable drawcord waist.",
  },
  {
    name: "Cropped Knit Cardigan",
    category: "women",
    price: 1250,
    compareAtPrice: null,
    isNew: true,
    inStock: true,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Cream", "Gold", "Black"],
    images: [img("night-cardigan-1"), img("night-cardigan-2")],
    description: "Soft knit cardigan with a cropped silhouette and horn-style buttons.",
  },
  {
    name: "Satin Slip Dress",
    category: "women",
    price: 1290,
    compareAtPrice: 1650,
    isNew: false,
    inStock: true,
    sizes: ["XS", "S", "M"],
    colors: ["Espresso", "Sand"],
    images: [img("night-dress-1"), img("night-dress-2")],
    description: "Bias-cut satin slip dress with adjustable straps. Fully lined.",
  },
  {
    name: "High-Rise Wide Jeans",
    category: "women",
    price: 1350,
    compareAtPrice: null,
    isNew: false,
    inStock: false,
    sizes: ["S", "M", "L"],
    colors: ["Washed Black"],
    images: [img("night-jeans-1")],
    description: "High-rise wide-leg denim with a clean, uncropped hem.",
  },
  {
    name: "Kids Graphic Hoodie",
    category: "kids",
    price: 600,
    compareAtPrice: 750,
    isNew: false,
    inStock: true,
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Gold", "Cream"],
    images: [img("night-kids-hoodie-1")],
    description: "Soft fleece hoodie with a front kangaroo pocket and print graphic.",
  },
  {
    name: "Kids Jogger Set",
    category: "kids",
    price: 850,
    compareAtPrice: null,
    isNew: true,
    inStock: true,
    sizes: ["2-3Y", "4-5Y", "6-7Y"],
    colors: ["Sand", "Black"],
    images: [img("night-kids-jogger-1")],
    description: "Two-piece jogger set in brushed cotton, built for everyday play.",
  },
  {
    name: "Essential Crewneck Sweatshirt",
    category: "men",
    price: 750,
    compareAtPrice: 950,
    isNew: false,
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Cream", "Espresso"],
    images: [img("night-crewneck-1")],
    description: "Midweight fleece crewneck with ribbed cuffs and hem. A wardrobe staple.",
  },
];
